name: test

services:
  angular:
    container_name: angular
    command: sh -c "npm install && npx ng serve --host 0.0.0.0"
    image: node:22.17.0-alpine
    ports:
      - 4200:4200
    volumes:
      - ./angular:/home/node/angular
    working_dir: /home/node/angular

  fastapi:
    build:
      dockerfile: fastapi/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    container_name: fastapi
    environment:
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - 8000:8000
    volumes:
      - ./fastapi/app:/fastapi/app
      - ./fastapi/db.sqlite3:/fastapi/db.sqlite3
      - ./fastapi/requirements.txt:/fastapi/requirements.txt
    working_dir: /fastapi

  redis:
    command: redis-server
    container_name: redis
    image: redis:7.4.2
    expose:
      - 6379
    volumes:
      - redis:/data
    restart: always

volumes:
  redis:
    name: redis